---
- name: Get Templates Override Status
  hosts: panorama
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
    template_stacks:
      - Firewall_Incorrect_Stack
      - Firewall2_Incorrect_Stack
      - Firewall_Correct_Stack

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Gather facts for device
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"

    - name: Display information
      ansible.builtin.debug:
        msg:
          - "Hostname: {{ ansible_facts['net_hostname'] }}"
          - "Serial: {{ ansible_facts['net_serial'] }}"
          - "Model: {{ ansible_facts['net_model'] }}"
          - "Version: {{ ansible_facts['net_version'] }}"
          - "Uptime: {{ ansible_facts['net_uptime'] }}"
          - "HA Enabled: {{ ansible_facts['net_ha_enabled'] }}"
          - "HA Type: {{ ansible_facts['net_ha_localmode'] }}"
          - "HA Status: {{ ansible_facts['net_ha_localstate'] }}"
          - "Multi-VSYS: {{ ansible_facts['net_multivsys'] }}"
          #- "{{ ansible_facts['net_session_usage'] }} out of {{ ansible_facts['net_session_max'] }} sessions in use"
    
    - name: Get Template Stacks Info
      paloaltonetworks.panos.panos_template_stack:
        provider: "{{ device }}"
        name: "{{ item }}"
        state: 'gathered'
      register: stack_result_raw
      loop: "{{ template_stacks }}"
    
    - name: Extract gathered template stack data into a clean list
      ansible.builtin.set_fact:
        stack_result: >-
          {{
            stack_result_raw.results
            | map(attribute='gathered')
            | select('defined')
            | flatten
            | list
          }}

    - name: Output Results
      ansible.builtin.debug:
        var: stack_result