---
- name: Get Templates Override Status
  hosts: AOB-LFMC-1
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ panorama_username }}"
      password: "{{ panorama_password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Gather facts for device
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"

    - name: Query Panorama for managed devices
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "show devices all"
      register: panorama_devices_raw

    - name: Parse Panorama stdout JSON
      ansible.builtin.set_fact:
        panorama_devices_json: "{{ panorama_devices_raw.stdout | from_json }}"

    - name: Capture devices list from parsed stdout
      ansible.builtin.set_fact:
        panorama_devices_list: >-
          {{
            panorama_devices_json.response.result.devices.entry
            | default([])
          }}

    - name: Extract PA-4 devices (serial, mgmt_ip, model, template-stack) from Panorama output
      ansible.builtin.set_fact:
        fw_400_devices: >-
          {{
            (fw_400_devices | default([]))
            + [ {
              'hostname': item.hostname | default(''),
              'serial': item.serial | default(''),
              'mgmt_ip': item['ip-address'] | default(''),
              'model': item.model | default(''),
            } ]
          }}
      loop: "{{ panorama_devices_list }}"
      when:
        - item.model is defined
        - item.model is string
        - item.model.startswith('PA-4')

    - name: Debug discovered 400-series devices
      ansible.builtin.debug:
        var: fw_400_devices

    - name: Build serial -> mgmt IP map for 400-series devices
      ansible.builtin.set_fact:
        fw_400_by_serial: >-
          {{
            (fw_400_by_serial | default({}))
            | combine({ item.serial: item.mgmt_ip })
          }}
      loop: "{{ fw_400_devices }}"

    - name: Gather all template stacks
      paloaltonetworks.panos.panos_template_stack:
        provider: "{{ device }}"
        state: gathered
        gathered_filter: '*'
      register: template_stack_result_raw_all

    - name: Debug discovered 400-series devices
      ansible.builtin.debug:
        var: template_stack_result_raw_all

    - name: Normalize gathered template stacks into a list
      ansible.builtin.set_fact:
        template_stack_all: "{{ template_stack_result_raw_all.gathered | default([]) }}"

    - name: Debug discovered 400-series devices
      ansible.builtin.debug:
        var: template_stack_all

    - name: Build list of 400-series serials
      ansible.builtin.set_fact:
        fw_400_serials: "{{ fw_400_devices | map(attribute='serial') | list }}"

    - name: Debug discovered 400-series devices
      ansible.builtin.debug:
        var: fw_400_serials

    - name: Build template stacks with 400-series member firewalls
      ansible.builtin.set_fact:
        template_stacks_with_400: >-
          {{
            (template_stacks_with_400 | default([]))
            + [ {
              'stack': item.name | default(''),
              'templates': item.templates | default([]),
              'member_firewalls': (
                (
                  ((item.devices | default(item.device | default([]))) | length > 0
                    and ((item.devices | default(item.device | default([]))) | first) is mapping)
                  | ternary(
                      (
                        (item.devices | default(item.device | default([])))
                        | map(attribute='serial')
                        | list
                      ),
                      (item.devices | default(item.device | default([])))
                    )
                )
                | intersect(fw_400_serials | default([]))
              )
            } ]
          }}
      loop: "{{ template_stack_all }}"
      when:
        - item is mapping
        - (
            (
              ((item.devices | default(item.device | default([]))) | length > 0
                and ((item.devices | default(item.device | default([]))) | first) is mapping)
              | ternary(
                  (
                    (item.devices | default(item.device | default([])))
                    | map(attribute='serial')
                    | list
                  ),
                  (item.devices | default(item.device | default([])))
                )
            )
            | intersect(fw_400_serials | default([]))
            | length
          ) > 0

    - name: Derive template stacks from template stack membership
      ansible.builtin.set_fact:
        template_stacks: "{{ template_stacks_with_400 | map(attribute='stack') | unique | list }}"

    - name: Debug discovered 400-series devices
      ansible.builtin.debug:
        var: template_stacks

    - name: Build mapping of template_stack -> mgmt IPs for 400-series firewalls
      ansible.builtin.set_fact:
        fw_400_by_stack: >-
          {{
            (fw_400_by_stack | default({}))
            | combine({
                item.stack: (
                  (item.member_firewalls | default([]))
                  | map('extract', fw_400_by_serial | default({}))
                  | select('defined')
                  | list
                )
              })
          }}
      loop: "{{ template_stacks_with_400 }}"

    - name: Get Template Stacks Info
      paloaltonetworks.panos.panos_template_stack:
        provider: "{{ device }}"
        name: "{{ item }}"
        state: 'gathered'
      register: template_stack_result_raw
      loop: "{{ fw_400_by_stack.keys() | list }}"
    
    - name: Extract gathered template stack data into a clean list
      ansible.builtin.set_fact:
        template_stack_result: >-
          {{
            template_stack_result_raw.results
            | map(attribute='gathered')
            | select('defined')
            | flatten
            | list
          }}
    
    - name: Map template stack name to first template
      ansible.builtin.set_fact:
        template_stack_to_template: >-
          {{
            template_stack_to_template | default({})
            | combine({
                item.name: (item.templates | first)
              })
          }}
      loop: "{{ template_stack_result }}"
      when:
        - item.templates is defined
        - item.templates | length > 0

    - name: Map template stack name to global template
      ansible.builtin.set_fact:
        template_stack_to_global: >-
          {{
            template_stack_to_global | default({})
            | combine({
                item.name: (item.templates | last)
              })
          }}
      loop: "{{ template_stack_result }}"
      when:
        - item.templates is defined
        - item.templates | length > 0

    - name: Pull management permitted IPs from template + template stack
      vars:
        template_xpath: >-
          /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='{{ template_stack_to_global[item] }}']
          /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/permitted-ip
        stack_xpath: >-
          /config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='{{ item }}']
          /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/permitted-ip
      block:

        - name: Get permitted IPs from GLOBAL TEMPLATE in the stack
          paloaltonetworks.panos.panos_type_cmd:
            provider: "{{ device }}"
            cmd: "get"
            xpath: "{{ template_xpath | regex_replace('\\s+', '') }}"
          register: template_stack_permitted_from_template_raw
          loop: "{{ fw_400_by_stack.keys() | list }}"
          loop_control:
            loop_var: item
            label: "stack={{ item }} template={{ template_stack_to_global[item] }}"

        - name: Get permitted IPs from TEMPLATE STACK config
          paloaltonetworks.panos.panos_type_cmd:
            provider: "{{ device }}"
            cmd: "get"
            xpath: "{{ stack_xpath | regex_replace('\\s+', '') }}"
          register: template_stack_permitted_from_stack_raw
          loop: "{{ fw_400_by_stack.keys() | list }}"
          loop_control:
            loop_var: item
            label: "stack={{ item }}"

        # Parse XML -> list of entry names (IP/subnet). This is the key extraction.
        # We look for: <entry name="1.2.3.4/32"> or <entry name="10.0.0.0/8">
        - name: Build a per-stack report (stack, template, template_permitted_ips, stack_permitted_ips)
          ansible.builtin.set_fact:
            template_stack_mgmt_permitted_ips: >-
              {{
                template_stack_mgmt_permitted_ips | default([])
                + [ {
                  'stack': item,
                  'template': template_stack_to_global[item],
                  'template_permitted_ips': (
                    (template_stack_permitted_from_template_raw.results
                      | selectattr('item', 'equalto', item)
                      | map(attribute='stdout_xml')
                      | first
                      | default('')
                    )
                    | regex_findall('entry name="([^\"]+)"')
                    | list
                  ),
                  'stack_permitted_ips': (
                    (template_stack_permitted_from_stack_raw.results
                      | selectattr('item', 'equalto', item)
                      | map(attribute='stdout_xml')
                      | first
                      | default('')
                    )
                    | regex_findall('entry name="([^\"]+)"')
                    | list
                  )
                } ]
              }}
          loop: "{{ fw_400_by_stack.keys() | list }}"

    - name: Compute missing permitted IPs (template not present in stack)
      ansible.builtin.set_fact:
        template_stack_permitted_ip_compliance: >-
          {{
            (template_stack_permitted_ip_compliance | default([]))
            + [ item | combine({
                'missing_in_stack': (
                  (item.template_permitted_ips | default([]))
                  | difference(item.stack_permitted_ips | default([]))
                )
              })
              ]
          }}
      loop: "{{ template_stack_mgmt_permitted_ips }}"

    - name: Validate stack overrides against actual firewall mgmt IPs
      ansible.builtin.set_fact:
        template_stack_override_validation: >-
          {{
            (template_stack_override_validation | default([]))
            + [ {
                'stack': item.stack,
                'expected_mgmt_ips': (fw_400_by_stack[item.stack] | default([])),
                'overridden_ips': (
                  (item.stack_permitted_ips | default([]))
                  | difference(item.template_permitted_ips | default([]))
                ),
                'missing_in_override': (
                  (fw_400_by_stack[item.stack] | default([]))
                  | difference(
                      (item.stack_permitted_ips | default([]))
                      | difference(item.template_permitted_ips | default([]))
                    )
                ),
                'extra_in_override': (
                  (
                    (item.stack_permitted_ips | default([]))
                    | difference(item.template_permitted_ips | default([]))
                  )
                  | difference(fw_400_by_stack[item.stack] | default([]))
                )
              } ]
          }}
      loop: "{{ template_stack_mgmt_permitted_ips }}"

    - name: Build dict of stack -> issue details for output
      ansible.builtin.set_fact:
        template_stack_issues_by_stack: >-
          {{
            (template_stack_issues_by_stack | default({}))
            | combine({
                item.stack: {
                  'expected_mgmt_ips': (item.expected_mgmt_ips | default([])),
                  'overridden_ips': (item.overridden_ips | default([])),
                  'missing_in_override': (item.missing_in_override | default([])),
                  'extra_in_override': (item.extra_in_override | default([]))
                }
              })
          }}
      loop: "{{ template_stack_override_validation }}"

    - name: Debug stack issues dict
      ansible.builtin.debug:
        var: template_stack_issues_by_stack

    - name: Publish stack issues for downstream workflow nodes
      ansible.builtin.set_stats:
        data:
          template_stack_issues_by_stack: "{{ template_stack_issues_by_stack | default({}) }}"
        per_host: false
        aggregate: false

























