---
- name: Remediate template stack management ACL overrides
  hosts: "{{ workflow_target_host }}"
  connection: local
  gather_facts: false

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ panorama_username }}"
      password: "{{ panorama_password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Ensure remediation stack payload is provided
      ansible.builtin.assert:
        that:
          - template_stacks_requiring_override_fix is defined
        fail_msg: "template_stacks_requiring_override_fix is required."

    - name: Normalize remediation stack payload to a mapping
      ansible.builtin.set_fact:
        template_stacks_requiring_override_fix_payload: >-
          {{
            template_stacks_requiring_override_fix
            if template_stacks_requiring_override_fix is mapping
            else (template_stacks_requiring_override_fix | from_yaml)
          }}

    - name: Build remediation plan as stacks in question
      ansible.builtin.set_fact:
        stack_remediation_plan: "{{ template_stacks_requiring_override_fix_payload.keys() | list }}"

    - name: Show remediation plan
      ansible.builtin.debug:
        var: stack_remediation_plan

    - name: Remove current management ACL override from each stack
      vars:
        stack_permitted_ip_xpath: >-
          /config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='{{ item }}']
          /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/permitted-ip
      paloaltonetworks.panos.panos_type_cmd:
        provider: "{{ device }}"
        cmd: delete
        xpath: "{{ stack_permitted_ip_xpath | regex_replace('\\s+', '') }}"
      register: stack_override_delete_result
      loop: "{{ stack_remediation_plan | default([]) }}"
      failed_when: false

    - name: Publish remediation results for downstream workflow nodes
      ansible.builtin.set_stats:
        data:
          stack_remediation_plan: "{{ stack_remediation_plan | default([]) }}"
          stack_override_delete_result: "{{ stack_override_delete_result.results | default([]) }}"
        per_host: false
        aggregate: false
