---
- name: Set Panorama template stack variables for firewall management IPs
  hosts: "{{ workflow_target_host }}"
  connection: local
  gather_facts: false

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ panorama_username }}"
      password: "{{ panorama_password }}"
    mgmt_variable_names:
      - '$fw-mgmt-ip-a'
      - '$fw-mgmt-ip-b'

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Ensure remediation stack payload is provided
      ansible.builtin.assert:
        that:
          - template_stacks_requiring_override_fix is defined
        fail_msg: "template_stacks_requiring_override_fix is required."

    - name: Normalize remediation stack payload to a mapping
      ansible.builtin.set_fact:
        template_stacks_requiring_override_fix_payload: >-
          {{
            template_stacks_requiring_override_fix
            if template_stacks_requiring_override_fix is mapping
            else (template_stacks_requiring_override_fix | from_yaml)
          }}

    - name: Build stack and management IP source list
      ansible.builtin.set_fact:
        stack_mgmt_ip_source: >-
          {{
            (stack_mgmt_ip_source | default([]))
            + [ {
              'stack': item.key,
              'expected_mgmt_ips': (
                item.value.expected_mgmt_ips
                | default([])
                | select('string')
                | map('trim')
                | reject('equalto', '')
                | map('regex_replace', '^(\\d+\\.\\d+\\.\\d+\\.\\d+)$', '\\1/32')
                | unique
                | list
              )
            } ]
          }}
      loop: "{{ template_stacks_requiring_override_fix_payload | dict2items }}"

    - name: Build variable entry for management IP A
      ansible.builtin.set_fact:
        stack_variable_entries: >-
          {{
            (stack_variable_entries | default([]))
            + [ {
              'stack': item.stack,
              'ip': item.expected_mgmt_ips[0],
              'variable_name': mgmt_variable_names[0]
            } ]
          }}
      loop: "{{ stack_mgmt_ip_source | default([]) }}"
      when: (item.expected_mgmt_ips | default([]) | length) > 0

    - name: Build variable entry for management IP B
      ansible.builtin.set_fact:
        stack_variable_entries: >-
          {{
            (stack_variable_entries | default([]))
            + [ {
              'stack': item.stack,
              'ip': item.expected_mgmt_ips[1],
              'variable_name': mgmt_variable_names[1]
            } ]
          }}
      loop: "{{ stack_mgmt_ip_source | default([]) }}"
      when: (item.expected_mgmt_ips | default([]) | length) > 1

    - name: Show variable entries to configure
      ansible.builtin.debug:
        var: stack_variable_entries

    - name: Set stack variables for management IPs
      vars:
        variable_xpath: >-
          /config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='{{ item.stack }}']
          /variable/entry[@name='{{ item.variable_name }}']
      paloaltonetworks.panos.panos_type_cmd:
        provider: "{{ device }}"
        cmd: set
        xpath: "{{ variable_xpath | regex_replace('\\s+', '') }}"
        element: "<type><ip-netmask>{{ item.ip }}</ip-netmask></type>"
      loop: "{{ stack_variable_entries | default([]) }}"
      register: stack_variable_set_result

    - name: Publish stack variable update results for downstream workflow nodes
      ansible.builtin.set_stats:
        data:
          stack_variable_entries: "{{ stack_variable_entries | default([]) }}"
          stack_variable_set_result: "{{ stack_variable_set_result.results | default([]) }}"
        per_host: false
        aggregate: false
